version: 1

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  rotating_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: logs/wordle_solver.log  # This will be overridden in code
    when: midnight
    backupCount: 14  # Keep logs for 14 days
    encoding: utf8

loggers:
  wordle_solver:
    level: INFO
    handlers: [console, rotating_file_handler]
    propagate: False

root:
  level: INFO
  handlers: [console, rotating_file_handler]
  propagate: False
