# src/modules/backend/solver/constants.py
"""
Constants for the Wordle solver system to replace magic numbers throughout the codebase.
"""

# Game configuration constants
DEFAULT_MAX_ATTEMPTS = 6
DEFAULT_WORD_LENGTH = 5
DEFAULT_GAME_ID_LENGTH = 6

# Scoring and threshold constants
PERFECT_SCORE = 10.0
EXCELLENT_ENTROPY_THRESHOLD = float("inf")
MILLISECONDS_CONVERSION_FACTOR = 1000
ROUND_PRECISION_DIGITS = 2

# Performance optimization constants
DEFAULT_EARLY_TERMINATION_CHECK_INTERVAL = 20
MIN_EVALUATIONS_BEFORE_EARLY_TERMINATION = 40
DEFAULT_MAX_POSSIBLE_CANDIDATES = 100
DEFAULT_MAX_ADDITIONAL_COMMON_WORDS = 10

# Strategy-specific constants
TWO_STEP_MAX_PATTERNS_DEFAULT = 10
TWO_STEP_LARGE_SEARCH_THRESHOLD = 50
TWO_STEP_FEW_WORDS_THRESHOLD = 3
TWO_STEP_MAX_POSSIBLE_CANDIDATES = 20
TWO_STEP_MAX_ADDITIONAL_COMMON = 5
TWO_STEP_COUNT_MULTIPLIER = 2
TWO_STEP_SECOND_STEP_CANDIDATE_LIMIT = 10

# Minimax strategy constants
MINIMAX_PERFORMANCE_CANDIDATE_LIMIT = 25
MINIMAX_LARGE_CANDIDATE_THRESHOLD = 50
MINIMAX_MAX_CANDIDATES_FOR_EFFICIENCY = 1000
MINIMAX_MAX_ADDITIONAL_CANDIDATES = 500

# Weighted gain strategy constants
WEIGHTED_GAIN_MAX_POSSIBLE_CANDIDATES = 50
WEIGHTED_GAIN_MAX_ADDITIONAL_COMMON = 10
WEIGHTED_GAIN_LARGE_WORDLIST_THRESHOLD = 50

# Common utility constants
COMMON_WORDS_HALF_RATIO = 2  # For dividing count by 2
ENTROPY_EVALUATION_BATCH_SIZE = 20
ENTROPY_MIN_EVALUATIONS = 40

# Logging and array indexing constants
FIRST_ARRAY_INDEX = 0
SECOND_ARRAY_INDEX = 1
THIRD_ARRAY_INDEX = 2
FOURTH_ARRAY_INDEX = 3
FIFTH_ARRAY_INDEX = 4
SKIP_SELF_PARAMETER_INDEX = 1

# Default suggestion counts
DEFAULT_SUGGESTIONS_COUNT = 10

# Default weight values for weighted strategies
DEFAULT_ENTROPY_WEIGHT = 0.6
DEFAULT_POSITIONAL_WEIGHT = 0.3
DEFAULT_FREQUENCY_WEIGHT = 0.1
WEIGHT_DISPLAY_PRECISION = 1

# Backup and configuration constants
DEFAULT_BACKUP_COUNT = 30

# Encoding constants
DEFAULT_ENCODING = "utf-8"

# Version constants
VERSION_MAJOR = 2
VERSION_MINOR = 0
VERSION_PATCH = 0
