---
# Logging configuration for Wordle Solver application with daily file rotation
version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  rotating_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    filename: null  # Will be set dynamically in code
    when: 'midnight'
    interval: 1
    backupCount: 30  # Keep logs for 30 days
    encoding: 'utf8'

  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

loggers:
  wordle_solver:
    level: INFO
    handlers: [rotating_file_handler, console_handler]
    propagate: false

root:
  level: INFO
  handlers: [rotating_file_handler, console_handler]
