---
# Basic logging configuration for Wordle Solver application
version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: null  # Will be set dynamically in code

  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

loggers:
  wordle_solver:
    level: DEBUG
    handlers: [file_handler, console_handler]
    propagate: false

root:
  level: INFO
  handlers: [file_handler, console_handler]
