name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    name: Pre-commit Hooks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Cache pre-commit
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit (auto-fix)
      run: |
        # First run: auto-fix issues (may fail, that's expected)
        pre-commit run --all-files || true
        echo "Pre-commit auto-fixes completed"

    - name: Check if files were modified
      id: check-changes
      run: |
        if git diff --quiet; then
          echo "No changes made by pre-commit"
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "Files were modified by pre-commit"
          echo "changes=true" >> $GITHUB_OUTPUT
          git diff --name-only
        fi

    - name: Run pre-commit (verification)
      run: |
        # Second run: should pass if all issues were fixed
        echo "Running pre-commit verification..."
        pre-commit run --all-files

  documentation:
    name: Documentation Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"

    - name: Check README links
      run: |
        # Check for broken links in README (basic check)
        grep -o 'https\?://[^)]*' README.md | head -10 || echo "No links found"

    - name: Validate documentation structure
      run: |
        # Check that all referenced documentation files exist
        test -f docs/ARCHITECTURE.md
        test -f docs/Usage.md
        test -f docs/Requirements.md
        test -f CHANGELOG.md
